### ISSUE TITLE
Modify the way UE are connected and activated based on BS capacity, implementing the new scheduler.

### ISSUE THREAD

**Issue by brunohcfaria** [INDTSON/SHARC#17]

**Comment by gustavocidornelas** [comment]
SINR estimation for the DL done on commit 3bf4608

**Comment by gustavocidornelas** [comment]
SINR estimation for the UL done on commit 15991ca

**Comment by gustavocidornelas** [comment]
Mapping the SINR in the throughput per RB and first round of allocation done on commit 1e053f9

**Comment by gustavocidornelas** [comment]
First round of allocation properly working for both the UL and DL. Parameters K and M completely deleted. On commit 8bc7c95

**Comment by brunohcfaria** [comment]
- Moved the scheduler and support function the the specialized UL/DL classes
- Added another round of SINR estimation after first UE allocation done by the scheduler
- Distributed the remaining RBs in a round robin fashion
Commit 8479b90480107ee911c1428b963a10f5b760837a

**Comment by brunohcfaria** [comment]
Done in merge request #24
