### ISSUE TITLE
ue_num_rb going to extreme high value for low SINR in scheduler (UL)

### ISSUE THREAD

**Issue by brunohcfaria** [INDTSON/SHARC#20]
https://github.com/INDTSON/SHARC/blob/e728604e6754018e8a9c989a513064d5a3668a0d/sharc/simulation_imt_vale.py#L323

The value of `ue_num_rb` going to extreme high value for low SINR (UPLINK). This is because`get_thoughput_ul` return a very low value for throughput. 
The result of this is lacking of RB resources for further allocations.

**Comment by brunohcfaria** [comment]
One possible solution is when the UE has a very low SINR (hence the minimal data rate parameter is not satisfied) the scheduler doesn't allocate it. However, this is not an outage event, but lack of coverage.

**Comment by brunohcfaria** [comment]
Please, verify this in the DL also.

**Comment by gustavocidornelas** [comment]
This case happens when the throughput for the given SINR is supposed to be zero. Instead of setting the throughput to zero, a negligible value was used. It cannot set to zero due to the division done in the scheduler method.
